<?php

/**
 * @file
 * Module adds a guestbook to your site.
 */

/**
 * Implements hook_theme().
 */
function guestbook_theme($existing, $type, $theme, $path) {
  return [
    // Default template for a guesbook module.
    "guestbook_template" => [
      "variables" => [
        "form" => NULL,
        "feedbacks" => NULL,
      ],
    ],
    // Template for Feedbacks block.
    "feedbacks-template" => [
      "variables" => [
        "items" => NULL,
      ],
    ],
  ];
}
